### ISSUE TITLE
Decimal format problem when saving OSM Bounds

### ISSUE THREAD

**Issue by smirnovegorv** [topobyte/osm4j-xml#1]
XmlWriter class has a localization issue.
While decimal format used for writing coordinates is fixed and uses decimal point, the bounds object is written just using String.format with "%f" flag, without providing explicit locale (and thus using a system default one).

In Russian (and some others) locales by default a comma is used as decimal separator. So once I save an OSM file I can not read it anymore as it has inconsistent delimiters: all coordinates use point but bounds use comma.

Please specify Locale.US (or any other locale with decimal point) explicitly in XmlWriter.templateBounds field to force it use consistent delimiters everywhere in a generated file.

By the way, it will also be nice to make OsmOutputStream implement AutoClosable to be able to work with try-with-resource blocks.

**Comment by sebkur** [comment]
Thanks, I'll look into it!

**Comment by sebkur** [comment]
Sorry it took so long. Fixed it in version 0.1.3 and also added versions of all tests that run using different locales to avoid such issues in the future.

**Comment by smirnovegorv** [comment]
Great, thank you!
